
```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
library(tidyverse)
library(exams)
library(bayestestR)
library(bain)

true_d <- as.numeric(format(round(runif(1,-.05,.4),2), scientific = FALSE))
N <- sample(180:200, 1)

data <- tibble(
  Gruppe = c(rep("Kontrollgruppe", N), rep("Interventionsgruppe", N)),
  Posttest = c(distribution_normal(N) + 20, distribution_normal(N, true_d) + 20)
)

p_value <- numeric(0)
test <- t_test(Posttest ~ Gruppe, 
                  data = data)
p_value <- test$p.value

BF <- numeric(0)
BF <- bain(test,
           "groupKontrollgruppe = groupInterventionsgruppe; groupKontrollgruppe > groupInterventionsgruppe")$BFmatrix[1,2]

round_BF <- function(x){
  ifelse(x > 100, "> 100",
         ifelse(x > 10, round(x, 0),
                ifelse(x > 3, round(x, 1),
                       ifelse( x > 1/3, round(x, 2), 
                               ifelse(x > 1/10, round(x, 3), 
                                      ifelse(x > 1/100, round(x, 4), "< 0.01"))))))
}

round_p <- function(x){
  ifelse(x < 0.001, "< .001", round(x, 3))
}

sample_effect <- sample(c("Cliff's d", "Cohen's d"),1)
sample_inferencestatistic <- sample(c("p-Wert", "Bayes Faktor BF~10~"),1)

question_string_part1 <- 
      sample(c(
        "Es soll untersucht werden, inwiefern die Notenvergabe einem s.g. Grading Bias unterliegt (also einer unfairen Vergabe von Noten aufgrund von Merkmalen der Schüler:innen, bspw. aufgrund des Geschlechts). Eine Stichprobe von Lehrkräften wird darum gebeten, dieselben sechs Abiturprüfungen zu bewerten. Dabei werden die Lehrkräfte zufällig zwei Gruppen zugewiesen, wobei die Interventionsgruppe Informationen über das Geschlecht der dahinterstehenden Schüler:innen erhält, die Kontrollgruppe jedoch nicht. Es wird überprüft, ob Lehrkräfte mit Kenntnis über das Geschlecht systematisch den Schülerinnen oder den Schülern zu gute Noten geben im Vergleich zu den Bewertungen durch Lehrkräften ohne Kenntnis über das Geschlecht.",
        "Es soll untersucht werden, ob formatives Feedback ('Du kannst Plusaufgaben schon sicher über den Zehner, übe doch als nächstes dieses Blatt mit Minusaufgaben über den Zehner') lernförderlicher ist als summatives Feedback ('Für die Plusaufgaben erhältst du eine 2+, für die Minusaufgaben eine 3-4'). Dazu werden Lehrer:innen zufällig zwei Gruppen zugewiesen. Die Interventionsgruppe wird dazu aufgefordert, ausschließlich formatives Feedback über die Dauer von 3 Wochen zu geben. Die Kontrollgruppe soll ausschließlich summatives Feedback nach den 3 Wochen geben. Es wird untersucht, ob sich die Leistung der Schüler:innen nach diesem Zeitraum voneinander unterscheidet.",
        "Konstruktive Unterstützung gilt als zentrales Qualitätsmerkmal von Unterricht. Es sollen genauere Erkenntnisse darüber gewonnen werden, ob sich konstruktiv unterstützendes Unterrichten positiv auf die Motivation der Schüler:innen auswirkt. Dazu werden aus einem Pool von Lehrkräften zufällig 50 Personen ausgewählt, die zu einer Fortbildung zum Thema „konstruktive Unterstützung“ eingeladen werden (Interventionsgruppe). Die nicht eingeladenen Lehrkräfte werden als Kontrollgruppe genutzt. Nach der Fortbildung wird die Motivation der Schüler:innen aller beteiligten Lehrkräfte mithilfe von Fragebögen gemessen und zwischen Klassen, deren Lehrkraft die Fortbildung besucht haben, und Klassen, die der Kontrollgruppe angehören, verglichen."),
        1)

question_string_part2 <-
  paste("Ein Vergleich der beiden Gruppen ergibt ein",
        sample_effect,
        "=",
        true_d,
        "zugunsten der Interventionsgruppe mit einem",
        sample_inferencestatistic,
        "von",
        ifelse(sample_inferencestatistic == "p-Wert", round_p(p_value), round_BF(BF)),
        "für die Nullhypothese H~0~: d = 0 und die Alternativhypothese H~A~: d > 0.")


if (sample_inferencestatistic == "p-Wert") {
  answerlistdata <-
    tibble(
      answerlist = c(
        paste("Der Wert",round_p(p_value),"gibt die Größe des Effekts in der Stichprobe an."),
        ifelse(true_d < .05, paste("Da",true_d,"kleiner als das α-Niveau von .05 ist, kann *H~0~* zugunsten von *H~A~* verworfen werden."),
                                   paste("Da",true_d,"größer oder gleich dem α-Niveau von .05 ist, ist das Ergebnis inkonklusiv.")),
        "Die Alternativhypothese ist wahr.",
        "Die Nullhypothese ist wahr."),
      exsolution = c(F,F,F,F)
      ) |>
    #sample_n(3) |>
    add_row(answerlist = ifelse(p_value < .05, 
                                paste("Da",round_p(p_value),"kleiner als das α-Niveau von .05 ist, kann *H~0~* zugunsten von *H~A~* verworfen werden."),
                                      paste("Da",round_p(p_value),"größer oder gleich dem α-Niveau von .05 ist, ist das Ergebnis inkonklusiv.")),
                exsolution = T)
  } else{
    answerlistdata <-
      tibble(
      answerlist = c(
        paste("Der Wert",round_BF(BF),"gibt die Größe des Effekts in der Stichprobe an."),
        ifelse(3 < true_d && true_d < 10, paste("Da",true_d," zwischen 3 und 10 liegt, liegt moderate Evidenz für die Alternativhypothese (Cohen's d > 0) vor."),
                                   ifelse(true_d >= 10,paste("Da",true_d,"größer oder gleich dem Wert 10 ist, liegt starke Evidenz für die Alternativhypothese (Cohen's d > 0) vor."),
                                          ifelse(1/10 < true_d && true_d < 1/3, paste("Da",true_d," zwischen 1/10 und 1/3 liegt, liegt moderate Evidenz für die Nullhypothese (Cohen's d = 0) vor."),
                                                 ifelse(true_d <= 1/3, paste("Da",true_d,"kleiner oder gleich dem Wert 1/3 ist, liegt starke Evidenz für die Nullhypothese (Cohen's d = 0) vor."),
                                                        ifelse(1/3 < true_d && true_d < 3, paste("Da",true_d,"zwischen 1/3 und 3 liegt, ist das Ergebnis inkonklusiv.")))))),
        "Die Alternativhypothese ist wahr.",
        "Die Nullhypothese ist wahr."),
      exsolution = c(F,F,F,F)
      ) |>
    #sample_n(3) |>
    add_row(answerlist = ifelse(3 < round_BF(BF) && round_BF(BF) < 10, paste("Da",round_BF(BF)," zwischen 3 und 10 liegt, liegt moderate Evidenz für die Alternativhypothese (Cohen's d > 0) vor."),
                                   ifelse(round_BF(BF) >= 10,paste("Da",round_BF(BF),"größer oder gleich dem Wert 10 ist, liegt starke Evidenz für die Alternativhypothese (Cohen's d > 0) vor."),
                                          ifelse(1/10 < round_BF(BF) && roundBF(BF) < 1/3, paste("Da",round_BF(BF)," zwischen 1/10 und 1/3 liegt, liegt moderate Evidenz für die Nullhypothese (Cohen's d = 0) vor."),
                                                 ifelse(round_BF(BF) <= 1/3, paste("Da",round_BF(BF),"kleiner oder gleich dem Wert 1/3 ist, liegt starke Evidenz für die Nullhypothese (Cohen's d = 0) vor."),
                                                        ifelse(1/3 < round_BF(BF) && round_BF(BF) < 3, paste("Da",round_BF(BF),"zwischen 1/3 und 3 liegt, ist das Ergebnis inkonklusiv.")))))),
                exsolution = T)
  }

```


Question
========
`r paste(question_string_part1, question_string_part2)`

**Welche Aussage ist zutreffend?** 

  
```{r questionlist, echo = FALSE, results = "asis"}
answerlist(answerlistdata$answerlist, 
           markup = "markdown")
```




Meta-information
================
exname: Inferenzstatistik & Deskriptivstatistik trennen und interpretieren
extype: schoice
exsolution: `r mchoice2string(answerlistdata$exsolution)`
exshuffle: true