```{r data generation, echo = FALSE, results = "hide", message=FALSE}
library(tidyverse)
library(babynames)
library(exams)
soll_homomorph_generiert_werden <- sample(c("ja", "nein"), 1)

list_of_distinct_codes <- sample(c(-100:100, 
                                 c(-100:100 + runif(201))), 
                                 prob = c(rep(1,201), rep(.1,201)),
                                 size =1000,
                                 replace = T) %>% 
                          round(., 1) %>% 
                          unique(.)
code_Werkrealschule <- sample(list_of_distinct_codes[list_of_distinct_codes < 75], 1) 
code_Realschule <- code_Werkrealschule + sample(1:12, 1)
code_Gymnasium <- code_Realschule + sample(1:12, 1)
code_falsch <- sample(list_of_distinct_codes[list_of_distinct_codes > code_Realschule], 1) #später wird werkrea falsch
                 
data <- 
  babynames %>% 
  filter(prop >.01) %>% 
  slice_sample(n= 4) %>% 
  select(name, sex) %>% 
  mutate(`SchülerIn` = name,
         Grundschulempfehlung = sample(c("Werkrealschule", "Realschule", "Gymnasium"),
                                       4, replace = T)) %>% 
  left_join(.,
            tibble(Grundschulempfehlung = c("Werkrealschule", "Realschule", "Gymnasium"),
                   Messwert = c(code_Werkrealschule, code_Realschule, code_Gymnasium))
            )

if(soll_homomorph_generiert_werden == "nein"){
data$Messwert[1] <- code_falsch
data <- 
  data %>% 
  slice_sample(n= 4)
}
```


Question
========
Stellt die folgende Tabelle eine Messung der Grundschulempfehlung im Sinne eines Homomorphismus dar?

```{r, echo = F}
data %>% 
  select(SchülerIn, Grundschulempfehlung, Messwert) %>% 
  knitr::kable(., align = "c") %>% 
  kableExtra::kable_styling(full_width = F)
```



```{r questionlist, echo = FALSE, results = "asis"}
answerlist(c("ja", "nein"), 
           markup = "markdown")
```

Solution
========

```{r exsolutiongeneration, echo = F, results='hide'}
ex_solution <- case_when(soll_homomorph_generiert_werden == "ja" ~ c(T,F),
                         TRUE ~ c(F,T))
```



Meta-information
================
exname: Homomorphismus erkennen Grundschulempfehlung
extype: schoice
exsolution: `r mchoice2string(ex_solution)`