```{r, Datengenese, echo = FALSE, message=FALSE}
library(dplyr)
library(exams)
x <- sample(1:100, 7)
ad <- DescTools::MeanAD(x)
i <- sample(1:7,7)


round2 = function(x, n) {
    posneg = sign(x)
    z = abs(x)*10^n
    z = z + 0.5 + sqrt(.Machine$double.eps)
    z = trunc(z)
    z = z/10^n
    z*posneg
}

data <- tibble(
  answerlist = c(
    round2(ad + sample(c(-1,1), 1)*sd(x)*0.1, 2),
    round2(ad + sample(c(-1,1), 1)*sd(x)*0.15, 2),
    round2(ad + sample(c(-1,1), 1)*sd(x)*0.2, 2),
    round2(ad + sample(c(-1,1), 1)*sd(x)*0.25, 2),
    round2(ad + sample(c(-1,1), 1)*sd(x)*0.3, 2),
    round2(ad, 2)),
  exsolution = c(F,F,F,F,F,T)
) |> 
  sample_frac(1)
```    

Question
========
Berechnen Sie die Mean Average Deviation (MAD) der Datenreihe Y = (`r x[1]`, `r x[2]`, `r x[3]`, `r x[4]`, `r x[5]`, `r x[6]`, `r x[7]`).  




```{r questionlist, echo = FALSE, results='asis'}
answerlist(
  data |> pull(answerlist),
  markup = "markdown")
```




Meta-information
================
exname: AD berechnen
extype: schoice
exsolution: `r mchoice2string(data |> pull(exsolution))`