
```{r, echo=FALSE, results='hide', message=FALSE}
library(tidyverse)
library(exams)

# which context should be used for exp quasi-exp non-exp?
# nth_context <- 1

# create vignettes
pausen_nonexp <- "Es soll untersucht werden, welchen Zusammenhang es zwischen Pausen beim Lernen und der Lernleistung gibt. Dazu werden die Studierenden eines Seminars während ihrer Lernzeit beobachtet. Es wird registriert, wie viel Zeit sie für das Lernen der Inhalte aufwenden und wie viele Lernpausen sie machen. Die Lernleistung wird anhand der erreichten Punktzahl in einer Abschlussklausur bewertet."

pausen_quasiexp <- "Es soll untersucht werden, welchen Zusammenhang es zwischen Pausen beim Lernen und der Lernleistung gibt. Dazu werden Studentinnen und Studenten eines Seminars miteinander verglichen. Die Studentinnen werden aufgefordert nach jeweils 30 Minuten Lernzeit eine Pause von 5 Minuten einzulegen. Die Studenten sollen die Zeit ohne Unterbrechung zum Lernen nutzen. Zusätzlich wird die Lernzeit erfasst. Die Lernleistung wird anhand der erreichten Punktzahl in einer Abschlussklausur bewertet."

pausen_exp <- "Es soll untersucht werden, welchen Zusammenhang es zwischen Pausen beim Lernen und der Lernleistung gibt. Dazu werden die Studierenden in einem Seminar zufällig zwei Gruppen zugeteilt. Die Gesamtlernzeit wird für beide Gruppen auf 3 h begrenzt. Gruppe 1 soll nach jeweils 30 Minuten eine Pause von 5 Minuten machen, Gruppe 2 soll die Zeit ohne Unterbrechung zum Lernen nutzen. Die Lernleistung wird anhand der erreichten Punktzahl in einer Abschlussklausur bewertet."

anker_nonexp <- "Der Ankereffekt tritt ein, wenn Menschen mit neuen Informationen (z. B. Zahlenwerten) konfrontiert werden, die sie unbewusst als Anker nutzen, um daran ihre eigene Einschätzung zu orientieren. Es soll untersucht werden, ob die Zweitkorrektur von Abituraufsätzen im Fach Deutsch durch den Ankereffekt verfälscht wird, wenn die Erstkorrekturnote bekannt ist. Dazu werden einer repräsentativen Stichprobe von Deutschlehrkräften die gleichen fünf Deutschaufsätze samt Erstkorrektur mit der Bitte um Zweitkorrektur vorgelegt. Anschließend beantworten die Lehrkräfte in einem standardisierten Fragebogen, ob sie bei ihrer Beurteilung von der Erstkorrektur beeinflusst wurden."

anker_exp <- "Der Ankereffekt tritt ein, wenn Menschen mit neuen Informationen (z. B. Zahlenwerten) konfrontiert werden, die sie unbewusst als Anker nutzen, um daran ihre eigene Einschätzung zu orientieren. Es soll untersucht werden, ob die Zweitkorrektur von Abituraufsätzen im Fach Deutsch durch den Ankereffekt verfälscht wird, wenn die Erstkorrekturnote bekannt ist. Dazu werden Lehrer:innen zufällig in zwei Experimentalgruppen eingeteilt. Eine Gruppe erhält Deutschaufsätze mit einer angeblich guten Erstkorrekturnote (Note 2). Die andere Gruppe erhält dieselben Deutschaufsätze jedoch unter Angabe einer schlechten Erstkorrekturnote (Note 5). Es wird untersucht, ob eine bessere Note für Arbeiten mit der angeblichen guten Erstkorrekturnote als mit der angeblich schlechten Erstkorrekturnote vergeben werden."

anker_quasiexp <- "Der Ankereffekt tritt ein, wenn Menschen mit neuen Informationen (z. B. Zahlenwerten) konfrontiert werden, die sie unbewusst als Anker nutzen, um daran ihre eigene Einschätzung zu orientieren. Es soll untersucht werden, ob die Zweitkorrektur von Abituraufsätzen im Fach Deutsch durch den Ankereffekt verfälscht wird, wenn die Erstkorrekturnote bekannt ist. Der Einfachheit halber bilden die Lehrkräfte an Schule A die eine Experimentalgruppe und die Lehrkräfte an Schule B die zweite Experimentalgruppe. Eine Gruppe erhält Deutschaufsätze mit einer angeblich guten Erstkorrekturnote (Note 2). Die andere Gruppe erhält dieselben Deutschaufsätze jedoch unter Angabe einer schlechten Erstkorrekturnote (Note 5). Es wird untersucht, ob eine bessere Note für Arbeiten mit der angeblichen guten Erstkorrekturnote als mit der angeblich schlechten Erstkorrekturnote vergeben werden."

stress_nonexp <- "Es sollen genauere Erkenntnisse darüber gewonnen werden, wie sich die Stressbewältigung bei Lehrkräften verbessern lässt. Dazu werden umfangreiche Fragebögen zu Persönlichkeitsmerkmalen, Wissen zu Stressbewältigungsstrategien sowie eigenem Stressempfinden bei Lehrkräften mit und ohne vorherige Burnout-Diagnose miteinander verglichen."

stress_exp <- "Es sollen genauere Erkenntnisse darüber gewonnen werden, wie sich die Stressbewältigung bei Lehrkräften verbessern lässt. Dazu werden aus einem Pool interessierter Lehrkräfte zufällig 30 Personen ausgewählt und zu einem Stressbewältigungstraining eingeladen. Die nicht eingeladenen Lehrkräfte wurden als Kontrollgruppe genutzt. Im Training wird umfangreiches Wissen zur Entstehung von Stress und zu Stressbewältigungsstrategien angeboten und in kleineren Gruppenübungen vertieft. Längsschnittlich werden die Teilnehmenden zu ihrem eigenen Stressempfinden im Beruf befragt und mit der Kontrollstichprobe verglichen."

stress_quasiexp <- "Es sollen genauere Erkenntnisse darüber gewonnen werden, wie sich die Stressbewältigung bei Lehrkräften verbessern lässt. Dazu wird auf einer Fortbildung zum Thema Burnout für alle Teilnehmenden ein Stressbewältigungstraining in Kleingruppen durchgeführt. Die Kontrollstichprobe wird auf einer Fortbildung zum Thema Inklusion für die Studie ausgewählt. Längsschnittlich werden die Teilnehmenden anschließend zu ihrem eigenen Stressempfinden im Beruf befragt und mit der Kontrollstichprobe verglichen."


# create tibble with 
#   - column per topic
#   - first row exp, second row quasi-exp, third row non-exp
data <- tibble(design = c("exp", "quasi-exp", "non-exp"),
               pausen = c(pausen_exp, pausen_quasiexp, pausen_nonexp),
               anker = c(anker_exp, anker_quasiexp, anker_nonexp),
               stress = c(stress_exp, stress_quasiexp, stress_nonexp)) |> 
  # randomize topic
  relocate(1, sample(2:4, 3)) |> 
  # randomize order of designs
  sample_frac(1)

answerlist <- 
  c("Studie A = höchste interne Validität & Studie B niedrigste interne Validität",
    "Studie A = höchste interne Validität & Studie C niedrigste interne Validität",
    "Studie B = höchste interne Validität & Studie A niedrigste interne Validität",
    "Studie B = höchste interne Validität & Studie C niedrigste interne Validität",
    "Studie C = höchste interne Validität & Studie A niedrigste interne Validität",
    "Studie C = höchste interne Validität & Studie B niedrigste interne Validität")

exsolution <- 
  case_when(identical(data$design, c("exp", "non-exp", "quasi-exp")) ~ c(T,F,F,F,F,F),
            identical(data$design, c("exp", "quasi-exp", "non-exp")) ~ c(F,T,F,F,F,F),
            identical(data$design, c("non-exp", "exp", "quasi-exp")) ~ c(F,F,T,F,F,F),
            identical(data$design, c("quasi-exp", "exp", "non-exp")) ~ c(F,F,F,T,F,F),
            identical(data$design, c("non-exp", "quasi-exp", "exp")) ~ c(F,F,F,F,T,F),
            identical(data$design, c("quasi-exp", "non-exp", "exp")) ~ c(F,F,F,F,F,T))
```


Question
========
Im Folgenden werden drei verschiedene Studien zum selben Thema vorgestellt. Welche zeigt die höchste/niedrigste interne Validität?

**Studie A**
*`r data[1,2]`*

**Studie B**
*`r data[2,2]`*

**Studie C**
*`r data[3,2]`*

  
```{r questionlist, echo = FALSE, results='asis'}
answerlist(answerlist, markup = "markdown")
```

Solution
========


Meta-information
================
exname: IntVal_Exp_Quasiexp_Nichtexp_zuordnen
extype: schoice
exsolution: `r mchoice2string(exsolution)`