```{r, Datengenese, echo = FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(exams)

x_start <- sample(-20:20, 1)
x_diff1 <- sample(1:5, 1)
x_diff2 <- sample(1:5, 1)
x_diff3 <- sample(1:5, 1)
x_diff4 <- sample(1:5, 1)

x <- sort(c(x_start,
            x_start + x_diff1,
            x_start - x_diff2,
            x_start + x_diff3,
            x_start - x_diff4))
mean <- mean(x)

distractors <- sample(
  c(sample(-10:-1, 10),
    sample(1:10, 10)),
    5)

data <- tibble(
  answerlist = c(
    mean + distractors[1],
    mean + distractors[2],
    mean + distractors[3],
    mean + distractors[4],
    mean + distractors[5],
    mean),
  exsolution = c(F,F,F,F,F,T)
) |> 
  sample_frac(1)
```    

Question
========
Berechnen Sie das arithmetische Mittel (Mean) der Datenreihe Y = (`r x[1]`, `r x[2]`, `r x[3]`, `r x[4]`, `r x[5]`).  




```{r questionlist, echo = FALSE, results='asis'}
answerlist(
  data |> pull(answerlist),
  markup = "markdown")
```




Meta-information
================
exname: Mean berechnen
extype: schoice
exsolution: `r mchoice2string(data |> pull(exsolution))`