```{r data generation, echo = FALSE, results = "hide"}
library(tidyverse)
# library(exams)
Definitionen <- 
  c("Welches Gütekriterium befasst sich mit der Frage, ob ein Messinstrument tatsächlich genau das Merkmal erfasst, das es zu messen vorgibt?", #1
    "Welches Gütekriterium befasst sich mit der Frage, wie eindeutig die Befunde einer Studie Hinweise auf Ursache-Wirkungs-Verhältnisse geben können?", #2
    "Welches Gütekriterium befasst sich mit der Frage, inwieweit der vorgefundene Effekt auf andere Orte, Zeiten, Situationen und Personen generalisierbar ist?", #3
    "Welches Gütekriterium befasst sich mit der Frage, wie gut die verwendeten statistischen Datenanalysen zur Forschungsfrage und zum Datenmaterial passen?") #4

wievielte_Definition <- 2
```


Question
========
`r paste(Definitionen[wievielte_Definition])`



```{r questionlist, echo = FALSE, results = "asis"}
answerlist(c("Konstruktvalidität",
             "Interne Validität", 
             "Externe Validität", 
             "Statistische Validität"), 
           markup = "markdown")
```


```{r exsolutiongeneration, echo = F, results='hide'}
ex_solution <- case_when(wievielte_Definition == 1 ~ c(T,F,F,F),
                         wievielte_Definition == 2 ~ c(F,T,F,F),
                         wievielte_Definition == 3 ~ c(F,F,T,F),
                         wievielte_Definition == 4 ~ c(F,F,F,T))
```


Meta-information
================
exname: `r paste("Guetekriterium_in_Definition_erkennen", wievielte_Definition, sep = "_")`
extype: schoice
exsolution: `r mchoice2string(ex_solution)`
exshuffle: true