```{r data generation, echo = FALSE, results = "hide"}
library(tidyverse)
library(exams)

prompt <- sample(
  c("Welche der folgenden Maßnahmen sind zur Steigerung der **internen Validität** einer explanativen Studie geeignet?",
    "Welche der folgenden Maßnahmen sind zur Steigerung der **externen Validität** einer explanativen Studie geeignet?"),
  1
)

answerlistdata <-
  if (str_detect(prompt, "interne")) {
    tibble(
      answerlist = c(
        "Experimentelle Studiendesigns",
        "Längsschnittliche Studiendesigns",
        "Matching Studien",
        "Laborstudien",
        "Verblindung",
        "Kontroll- und Vergleichsgruppen",
        "Inferenzstatistik",
        "Direkte Replikationsstudien",
        "Präregistrierung",
        "Feldstudien"),
      exsolution = c(T, T, T, T, T, T, T, T, T, F)
    ) |>
      sample_n(5) |>
      add_row(answerlist = "Vergrößerung der Stichprobe",
              exsolution = T)
  } else{
    answerlistdata <-
      tibble(
        answerlist = c(
          "Laborstudien",
          "Verblindung",
          "Feldstudien",
          "Metaanalysen",
          "Vergrößerung der Stichprobe"
        ),
        exsolution = c(F, F, T, T, T)
      )
  }
```


Question
========
`r paste(prompt)`


```{r questionlist, echo = FALSE, results = "asis"}
answerlist(answerlistdata$answerlist, 
           markup = "markdown")
```


Meta-information
================
exname: Massnahmen_SteigerungInterneExterne_nachFolien
extype: mchoice
exsolution: `r mchoice2string(answerlistdata$exsolution)`
exshuffle: true