```{r, echo = FALSE, results = "hide", message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(exams)

# Q & A Matrix #################################################################
nth_task <- sample(1:20,1)

 q_a_matrix <- 
    tibble(
      Answers_and_Distractors = c("Es liegt eine signifikante (bei ⍺-Niveau = .05) Assoziation vor.",
                                  "Der vorliegende Effekt kann von den Daten auf die Population verallgemeinert werden.",
                                  "Der vorliegende Effekt kann nicht von den Daten auf die Population verallgemeinert werden.",
                                  
                                  "Es liegt Evidenz für die Nullhypothese (Kendall's τᵇ = 0) vor.",
                                  "Die Alternativhypothese ist wahr.", 
                                  "Die Nullhypothese ist wahr.",
                                  
                                  "Es liegt ein substantieller (mindestens kleiner) Effekt vor."),
      `Ein Forscher untersucht, inwiefern die tägliche Fernsehdauer mit der schulischen Leistung assoziiert ist. Dazu erhebt er beide Variablen bei N = 5805 Schülerinnen und Schülern und erhält ein Kendall's τᵇ von -.18 mit einem p < .001` =      
        c(1,1,NA, 0,0,NA, 1),
      
      `Ein Forscher untersucht, inwiefern die tägliche Fernsehdauer mit der schulischen Leistung assoziiert ist. Dazu erhebt er beide Variablen bei N = 24 Schülerinnen und Schüler und erhält ein Kendall's τᵇ von -.18 mit einem p = .426.` =      
        c(0,0,NA,  0,NA,0,  1),
      
      `Zwei Team-Klassenlehrerinnen vergeben unabhängig voneinander Grundschulempfehlungen (Werkrealschule, Realschule, Gymnasium) für N = 18 Schülerinnen und Schüler. Sie überprüfen die Übereinstimmung, indem sie Kendall's τᵇ berechnen. Dies liegt bei -.73 mit einem p = .426.` =      
        c(0,0,NA,  0,NA,0,  1),
      
      `Zwei Team-Klassenlehrerinnen vergeben über Jahre hinweg immer wieder unabhängig voneinander Grundschulempfehlungen für ihre gemeinsam unterrichteten vierten Klassen (Werkrealschule, Realschule, Gymnasium; insgesamt N = 148 Schülerinnen und Schüler. Sie überprüfen die Übereinstimmung, indem sie Kendall's τᵇ berechnen. Dies liegt bei -.73 mit einem p < .001.` =      
        c(1,1,NA,  0,0,NA,  1),
      
      `Ein Forscher untersucht, inwiefern der höchste Schulabschluss eines Probanden mit dem der Eltern des Probanden assoziiert ist. Dazu erhebt er beide Variablen bei N = 58 Studierenden und erhält ein Kendall's τᵇ von .3 mit einem p = .021.` =      
        c(1,1,NA, 0,0,NA, 1),
      `Ein Forscher untersucht, inwiefern der höchste Schulabschluss eines Probanden mit dem der Eltern des Probanden assoziiert ist. Dazu erhebt er beide Variablen bei N = 17 Studierenden und erhält ein Kendall's τᵇ von .3 mit einem p = .228.` =      
        c(0,NA,1, 0,NA,0, 1),
      `Ein Forscher untersucht, inwiefern der höchste Schulabschluss eines Probanden mit dem der Eltern des Probanden assoziiert ist. Dazu erhebt er beide Variablen bei N = 4312 Studierenden und erhält ein Kendall's τᵇ von .04 mit einem p = .008.` =      
        c(1,1,NA, 0,0,NA, 0),
      `Ein Forscher untersucht, inwiefern der höchste Schulabschluss eines Probanden mit dem der Eltern des Probanden assoziiert ist. Dazu erhebt er beide Variablen bei N = 125 Studierenden und erhält ein Kendall's τᵇ von .03 mit einem p = .75.` =      
        c(0,NA,1, 0,NA,0, 0),
      
      `Eine Studentin untersucht in ihrer Masterarbeit, inwiefern Pärchen nach einem gemeinsamen Restaurantbesuch ähnliche Onlinebewertungen für das Essen abgeben (0-5 Sterne). Dazu befragt sie N = 63 Pärchen und erhält ein Kendall's τᵇ von .28 mit einem p = .019.` =      
        c(1,1,NA, 0,0,NA, 1),
      `Eine Studentin untersucht in ihrer Masterarbeit, inwiefern Pärchen nach einem gemeinsamen Restaurantbesuch ähnliche Onlinbewertungen für das Essen abgeben (0-5 Sterne). Dazu befragt sie N = 17 Pärchen und erhält ein Kendall's τᵇ von .30 mit einem p = .318.` =      
        c(0,NA,1, 0,NA,0, 1),
      `Eine Studentin untersucht in ihrer Masterarbeit, inwiefern Pärchen nach einem gemeinsamen Restaurantbesuch ähnliche Onlinbewertungen für das Essen abgeben (0-5 Sterne). Dazu befragt sie N = 5312 Pärchen und erhält ein Kendall's τᵇ von .03 mit einem p = .007.` =      
        c(1,1,NA, 0,0,NA, 0),
      `Eine Studentin untersucht in ihrer Masterarbeit, inwiefern Pärchen nach einem gemeinsamen Restaurantbesuch ähnliche Onlinbewertungen für das Essen abgeben (0-5 Sterne). Dazu befragt sie N = 131 Pärchen und erhält ein Kendall's τᵇ von .04 mit einem p = .71.` =      
        c(0,NA,1, 0,NA,0, 0),
      
      `Ein Student untersucht in seiner Masterarbeit, inwiefern Pärchen ähnliche Ernährungsformen (0 = vegane Ernährung, 1 = ovo-lacto Vegetarismus, 2 = Vegetarismus, 3 = keine Einschränkung) zeigen. Dazu befragt er N = 65 Pärchen und erhält ein Kendall's τᵇ von .30 mit einem p = .019.` =      
        c(1,1,NA, 0,0,NA, 1),
      `Ein Student untersucht in seiner Masterarbeit, inwiefern Pärchen ähnliche Ernährungsformen (0 = vegane Ernährung, 1 = ovo-lacto Vegetarismus, 2 = Vegtarismus, 3 = keine Einschränkung) zeigen. Dazu befragt er N = 22 Pärchen und erhält ein Kendall's τᵇ von .29 mit einem p = .418.` =      
        c(0,NA,1, 0,NA,0, 1),
      `Ein Student untersucht in seiner Masterarbeit, inwiefern Pärchen ähnliche Ernährungsformen (0 = vegane Ernährung, 1 = ovo-lacto Vegetarismus, 2 = Vegtarismus, 3 = keine Einschränkung) zeigen. Dazu befragt er N = 3315 Pärchen und erhält ein Kendall's τᵇ von .02 mit einem p = .004.` =      
        c(1,1,NA, 0,0,NA, 0),
      `Ein Student untersucht in seiner Masterarbeit, inwiefern Pärchen ähnliche Ernährungsformen (0 = vegane Ernährung, 1 = ovo-lacto Vegetarismus, 2 = Vegtarismus, 3 = keine Einschränkung) zeigen. Dazu befragt er N = 1119 Pärchen und erhält ein Kendall's τᵇ von .03 mit einem p = .61.` =      
        c(0,NA,1, 0,NA,0, 0),
      
      `Ein Thinktank untersucht inwiefern Väter und Söhne sich auf einer Skala links - eher links - mitte - eher rechts - rechts politisch ähnlich verorten und befragt dazu N = 65 Väter mit ihren Söhnen. Die Daten zeigen ein Kendall's τᵇ von .35 mit einem p = .019.` =      
        c(1,1,NA, 0,0,NA, 1),
      `Ein Thinktank untersucht inwiefern Väter und Söhne sich auf einer Skala links - eher link - mitte - eher rechts - rechts politisch ähnlich verorten und befragt dazu N = 22 Väter mit ihren Söhnen. Die Daten zeigen ein Kendall's τᵇ von .28 mit einem p = .538.` =      
        c(0,NA,1, 0,NA,0, 1),
      `Ein Thinktank untersucht inwiefern Väter und Söhne sich auf einer Skala links - eher link - mitte - eher rechts - rechts politisch ähnlich verorten und befragt dazu N = 3315 Väter mit ihren Söhnen. Die Daten zeigen ein Kendall's τᵇ von .03 mit einem p = .002.` =      
        c(1,1,NA, 0,0,NA, 0),
      `Ein Thinktank untersucht inwiefern Väter und Söhne sich auf einer Skala links - eher link - mitte - eher rechts - rechts politisch ähnlich verorten und befragt dazu N = 1119 Väter mit ihren Söhnen. Die Daten zeigen ein Kendall's τᵇ von .03 mit einem p = .71.` =      
        c(0,NA,1, 0,NA,0, 0))

answers_and_distractors <- 
  q_a_matrix %>% 
  select(Answers_and_Distractors, nth_task + 1) %>% 
  na.omit() %>% 
  pull(Answers_and_Distractors)

correct_answers <- q_a_matrix %>% 
  select(Answers_and_Distractors, nth_task + 1) %>% 
  na.omit() %>% 
  pull(2)
```

Question
========
`r paste(names(q_a_matrix)[2:ncol(q_a_matrix)][nth_task])`


```{r questionlist, echo = FALSE, results='asis'}
answerlist(answers_and_distractors, markup = "markdown")
```

Meta-information
================
exname: Interpretation taub p
extype: mchoice
exsolution: `r mchoice2string(correct_answers)`




